site_name: STELLA - InfraSTructurEs for Living LAbs
site_url: https://example.com/
theme: 
    name: material
    logo: img/stella-logo.png
    favicon: img/favicon.ico 
nav:
    - Home: index.md
    - 'Guides': 
        - 'Setup guide (single server instance)': guides/single-machine.md    
    - About: about.md