site_name: STELLA
site_url: https://example.com/

theme:
  name: material
  logo: img/stella-logo.png
  favicon: img/favicon.ico
  icon:
    repo: fontawesome/brands/github
  features:
  - header.autohide
  - content.code.copy

  palette:
    primary: custom

extra_css:
- stylesheets/extra.css

markdown_extensions:
- admonition
- pymdownx.details
- pymdownx.superfences # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/  
- pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences

plugins:
- search

nav:
- Introduction:
  - introduction/overview.md
  - introduction/about.md
  - introduction/lilas-lab.md

- Researcher:
  - "Introduction": researcher/introduction.md
  - "Tutorial: Ranker": researcher/participants-ranking.md
  - "Tutorial: Recommender": researcher/participants-recommender-publications.md

- "Site Owner":
  - "Introduction": site-owner/introduction.md
  - "REST API":
    - "Micro-service": site-owner/micro-service.md
    - "STELLA-App": site-owner/mca.md
    - "STELLA-Server": site-owner/server.md

- Developer:
  - "Introduction": developer/introduction.md
  - "Setup for Local Developement": developer/initial_setup.md
  - "Environment variables":
    - "STELLA-App": developer/env-mca.md
    - "STELLA-Server": developer/env-server.md
  - "Common Issues": developer/common_issues.md

repo_url: https://github.com/stella-project
repo_name: stella-project
edit_uri: https://github.com/stella-project/stella-documentation/tree/master/docs
