site_name: STELLA - InfraSTructurEs for Living LAbs
site_url: https://example.com/
theme: 
    name: material
    logo: img/stella-logo.png
    favicon: img/favicon.ico 
    icon:
        repo: fontawesome/brands/github
    features:
        - header.autohide
        - navigation.top
    palette:
        primary: blue grey
        accent: amber
    font:
        text: Roboto
nav:
    - Home: index.md
    - 'Guides': 
        - 'Setup guide (single server instance)': guides/single-machine.md    
    - About: about.md
repo_url: https://github.com/stella-project
repo_name: stella-project
